"""Seed catalog for Gizmovo. All values are placeholders and are meant to be
replaced with real product data / Shopify data before going live."""
import uuid

CATEGORIES = [
    {"slug": "desk", "name": "Desk", "tagline": "Tidy, focused, and ready to work.",
     "image": "https://images.unsplash.com/photo-1644463589256-02679b9c0767?crop=entropy&cs=srgb&fm=jpg&q=85&w=1200"},
    {"slug": "audio", "name": "Audio", "tagline": "Sound that goes everywhere with you.",
     "image": "https://images.unsplash.com/photo-1608043152269-423dbba4e7e1?crop=entropy&cs=srgb&fm=jpg&q=85&w=1200"},
    {"slug": "home", "name": "Home", "tagline": "Small upgrades for everyday spaces.",
     "image": "https://images.unsplash.com/photo-1775331881925-ddae17afc69e?crop=entropy&cs=srgb&fm=jpg&q=85&w=1200"},
    {"slug": "everyday-carry", "name": "Everyday Carry", "tagline": "The stuff that lives in your bag.",
     "image": "https://images.unsplash.com/photo-1634839763563-97d93f8131c6?crop=entropy&cs=srgb&fm=jpg&q=85&w=1200"},
    {"slug": "travel", "name": "Travel", "tagline": "Light, useful, ready to move.",
     "image": "https://images.unsplash.com/photo-1732194392644-d1b9d92f90c8?crop=entropy&cs=srgb&fm=jpg&q=85&w=1200"},
]

CAT_NAME = {c["slug"]: c["name"] for c in CATEGORIES}


def _p(position, slug, name, tagline, category_slug, price, compare_at, images,
       short_benefit, description, story, benefits, how_it_works, specs, whats_included,
       variants=None, badge=None, best_seller=False, related=None, available=True):
    return {
        "id": str(uuid.uuid5(uuid.NAMESPACE_URL, "gizmovo/" + slug)),
        "position": position,
        "slug": slug,
        "name": name,
        "tagline": tagline,
        "category_slug": category_slug,
        "category": CAT_NAME[category_slug],
        "price": price,
        "compare_at_price": compare_at,
        "images": images,
        "short_benefit": short_benefit,
        "description": description,
        "story": story,
        "benefits": benefits,
        "how_it_works": how_it_works,
        "specs": specs,
        "whats_included": whats_included,
        "variants": variants or [],
        "badge": badge,
        "best_seller": best_seller,
        "available": available,
        "rating": None,
        "review_count": 0,
        "related": related or [],
    }


PRODUCTS = [
    _p(1, "aura-wireless-charger", "Aura Wireless Charger", "Charging, minus the cable mess.", "desk",
       1499, 1999,
       ["https://images.unsplash.com/photo-1633381638729-27f730955c23?crop=entropy&cs=srgb&fm=jpg&q=85&w=1200",
        "https://images.unsplash.com/photo-1631037561126-0782ab7e666e?crop=entropy&cs=srgb&fm=jpg&q=85&w=1200"],
       "Just set your phone down and it charges. No fumbling for cables.",
       "A slim charging pad that lives on your desk and keeps your phone topped up all day.",
       "Cables have a way of disappearing exactly when you need them. Aura fixes that — a single pad that's always in the same spot, always ready.",
       ["Fast 15W wireless charging", "Works through most cases", "Non-slip surface keeps your phone in place", "Soft light tells you it's charging"],
       ["Plug the pad in once and leave it on your desk", "Set your phone (or earbuds) on top", "It starts charging automatically"],
       [{"label": "Output", "value": "15W max"}, {"label": "Input", "value": "USB-C"}, {"label": "Compatibility", "value": "Qi-enabled phones"}, {"label": "Material", "value": "Aluminium + soft-touch top"}],
       ["Aura charging pad", "1m USB-C cable", "Quick start card"],
       variants=[{"name": "Colour", "options": ["Charcoal", "Beige"]}],
       badge="Best Seller", best_seller=True, related=["volt-gan-charger", "nook-desk-organizer", "peak-power-bank"]),

    _p(2, "pulse-wireless-earbuds", "Pulse Wireless Earbuds", "Your soundtrack, wire-free.", "audio",
       1999, 2999,
       ["https://images.unsplash.com/photo-1590658268037-6bf12165a8df?crop=entropy&cs=srgb&fm=jpg&q=85&w=1200",
        "https://images.unsplash.com/photo-1572569511254-d8f925fe2cbb?crop=entropy&cs=srgb&fm=jpg&q=85&w=1200"],
       "Deep sound, all-day battery, and a case that fits your pocket.",
       "Compact wireless earbuds tuned for everyday listening — calls, music, and everything in between.",
       "Most earbuds either sound flat or cost a fortune. Pulse sits right in the middle: genuinely good sound at a price that makes sense.",
       ["Rich, balanced sound", "Up to 24 hrs with the case", "Quick-pair Bluetooth", "Sweat-resistant for workouts"],
       ["Open the case next to your phone", "Tap to pair once", "Pop them in — they connect automatically after that"],
       [{"label": "Battery", "value": "6 hrs + 18 hrs case"}, {"label": "Bluetooth", "value": "5.3"}, {"label": "Water resistance", "value": "IPX4"}, {"label": "Charging", "value": "USB-C"}],
       ["Pulse earbuds", "Charging case", "3 ear-tip sizes", "USB-C cable"],
       badge="Best Seller", best_seller=True, related=["boom-portable-speaker", "peak-power-bank"]),

    _p(3, "boom-portable-speaker", "Boom Portable Speaker", "Big sound that travels light.", "audio",
       2499, 3499,
       ["https://images.unsplash.com/photo-1608043152269-423dbba4e7e1?crop=entropy&cs=srgb&fm=jpg&q=85&w=1200",
        "https://images.unsplash.com/photo-1589003077984-894e133dabab?crop=entropy&cs=srgb&fm=jpg&q=85&w=1200"],
       "Loud, clear, and small enough to throw in any bag.",
       "A pocket-sized Bluetooth speaker with surprisingly full sound and a battery that lasts the day out.",
       "Made for spontaneous moments — a terrace hangout, a beach afternoon, a room that needs music right now.",
       ["Room-filling sound", "12-hour battery", "Splash-proof for outdoors", "Pairs two for stereo"],
       ["Charge it up", "Connect over Bluetooth", "Press play and turn it up"],
       [{"label": "Battery", "value": "12 hrs"}, {"label": "Water resistance", "value": "IPX6"}, {"label": "Bluetooth", "value": "5.3"}, {"label": "Weight", "value": "340g"}],
       ["Boom speaker", "USB-C cable", "Wrist strap"],
       related=["pulse-wireless-earbuds", "peak-power-bank"]),

    _p(4, "nook-desk-organizer", "Nook Desk Organizer", "A home for the everyday clutter.", "desk",
       999, 1399,
       ["https://images.unsplash.com/photo-1644463589256-02679b9c0767?crop=entropy&cs=srgb&fm=jpg&q=85&w=1200"],
       "Keeps pens, cables, and your phone exactly where you can reach them.",
       "A compact organizer that gives every small thing on your desk a place to live.",
       "Your desk gets messy fast. Nook keeps the essentials within reach without taking over your workspace. Simple. Useful. Done.",
       ["Slots for phone, pens and cables", "Warm, tactile finish", "Compact footprint", "Non-scratch base"],
       ["Set it beside your keyboard", "Drop your daily items into the slots", "Enjoy a clearer desk"],
       [{"label": "Material", "value": "Bamboo + felt"}, {"label": "Size", "value": "22 x 11 x 6 cm"}, {"label": "Weight", "value": "260g"}],
       ["Nook organizer"],
       badge="New Drop", related=["aura-wireless-charger", "rise-laptop-stand"]),

    _p(5, "rise-laptop-stand", "Rise Laptop Stand", "Eye-level laptop, happier neck.", "desk",
       1799, 2499,
       ["https://images.unsplash.com/photo-1629317480826-910f729d1709?crop=entropy&cs=srgb&fm=jpg&q=85&w=1200",
        "https://images.unsplash.com/photo-1670761301241-7cec3cd6a925?crop=entropy&cs=srgb&fm=jpg&q=85&w=1200"],
       "Lifts your laptop to a comfortable height — and folds flat to carry.",
       "An aluminium stand that raises your screen to eye level and folds down to slip into your bag.",
       "Hours hunched over a laptop add up. Rise brings the screen to you, so your posture doesn't pay for your work.",
       ["Raises screen to eye level", "Folds flat for travel", "Vented for cooling", "Holds up to 16-inch laptops"],
       ["Unfold the stand", "Set your laptop on top", "Adjust to a comfortable angle"],
       [{"label": "Material", "value": "Aluminium alloy"}, {"label": "Fits", "value": "11-16 inch laptops"}, {"label": "Folded", "value": "1.5 cm thin"}],
       ["Rise stand", "Carry pouch"],
       variants=[{"name": "Colour", "options": ["Silver", "Space Grey"]}],
       best_seller=True, related=["nook-desk-organizer", "aura-wireless-charger"]),

    _p(6, "fresh-portable-blender", "Fresh Portable Blender", "Smoothies wherever you are.", "home",
       1699, 2299,
       ["https://images.unsplash.com/photo-1575499331636-6394e5ae7019?crop=entropy&cs=srgb&fm=jpg&q=85&w=1200",
        "https://images.unsplash.com/photo-1573613441815-270dc93f5c20?crop=entropy&cs=srgb&fm=jpg&q=85&w=1200"],
       "Blend, sip, and rinse — all from one bottle.",
       "A rechargeable blender bottle that makes a single-serve smoothie in seconds, then becomes the cup you drink from.",
       "Mornings are busy. Fresh turns fruit and a splash of milk into breakfast you can take with you — no bulky blender to clean.",
       ["Blends in 30 seconds", "USB-C rechargeable", "Doubles as a travel cup", "Easy to rinse"],
       ["Add fruit and liquid", "Press to blend", "Flip the lid and drink"],
       [{"label": "Capacity", "value": "380 ml"}, {"label": "Battery", "value": "~15 blends per charge"}, {"label": "Charging", "value": "USB-C"}, {"label": "Material", "value": "BPA-free Tritan"}],
       ["Fresh blender bottle", "USB-C cable", "Cleaning brush"],
       badge="New Drop", related=["ease-neck-massager", "glow-led-strip"]),

    _p(7, "glow-led-strip", "Glow LED Strip", "Set the mood in one tap.", "home",
       1299, 1799,
       ["https://images.unsplash.com/photo-1775331881925-ddae17afc69e?crop=entropy&cs=srgb&fm=jpg&q=85&w=1200",
        "https://images.unsplash.com/photo-1781865202580-408139ead247?crop=entropy&cs=srgb&fm=jpg&q=85&w=1200"],
       "Millions of colours, controlled from your phone.",
       "A stick-anywhere LED strip that turns a plain room into your kind of space.",
       "Lighting changes how a room feels. Glow lets you go from focused daylight to a warm evening scene without getting up.",
       ["16 million colours + scenes", "App and remote control", "Music-reactive mode", "Easy peel-and-stick"],
       ["Stick it behind your desk, bed or TV", "Plug it in", "Pick a colour from the app"],
       [{"label": "Length", "value": "5 metres"}, {"label": "Control", "value": "App + remote"}, {"label": "Power", "value": "USB / adapter"}],
       ["5m LED strip", "Remote", "Adapter", "Mounting clips"],
       best_seller=True, related=["fresh-portable-blender", "halo-motion-light"]),

    _p(8, "roll-cable-organizer", "Roll Cable Organizer", "Every cable, in its place.", "everyday-carry",
       799, 1099,
       ["https://images.unsplash.com/photo-1634839763563-97d93f8131c6?crop=entropy&cs=srgb&fm=jpg&q=85&w=1200",
        "https://images.unsplash.com/photo-1634839763121-58fcfed2a94a?crop=entropy&cs=srgb&fm=jpg&q=85&w=1200"],
       "The end of tangled cables in your bag.",
       "A slim roll-up pouch with elastic loops for chargers, cables, and the little things that always get lost.",
       "Reach into your bag and you'll find the cable, not a knot. Roll keeps your tech tidy and ready.",
       ["Elastic loops for cables and adapters", "Slim, bag-friendly design", "Water-resistant outer", "Zip pocket for small items"],
       ["Slot cables into the loops", "Roll it up and zip", "Drop it in your bag"],
       [{"label": "Material", "value": "Water-resistant nylon"}, {"label": "Size", "value": "24 x 12 cm rolled"}, {"label": "Weight", "value": "120g"}],
       ["Roll organizer"],
       related=["volt-gan-charger", "peak-power-bank"]),

    _p(9, "ease-neck-massager", "Ease Neck Massager", "Relief for the end of a long day.", "home",
       2299, 2999,
       ["https://images.unsplash.com/photo-1653840986487-c17987e2c0e5?crop=entropy&cs=srgb&fm=jpg&q=85&w=1200"],
       "Gentle warmth and pulses to loosen a stiff neck.",
       "A cordless neck massager that uses warmth and gentle pulses to ease tension after screens and commutes.",
       "Screens are hard on your neck. Ease gives you a few quiet minutes to reset — at your desk or on the couch.",
       ["Warmth + gentle pulse modes", "Cordless and rechargeable", "Adjustable intensity", "Auto-off timer"],
       ["Wear it around your neck", "Pick a mode and intensity", "Relax for 15 minutes"],
       [{"label": "Modes", "value": "6"}, {"label": "Battery", "value": "~90 min per charge"}, {"label": "Charging", "value": "USB-C"}],
       ["Ease massager", "USB-C cable", "Pouch"],
       related=["glow-led-strip", "fresh-portable-blender"]),

    _p(10, "volt-gan-charger", "Volt GaN Charger", "Charge three things from one tiny block.", "travel",
       1899, 2599,
       ["https://images.unsplash.com/photo-1583863788434-e58a36330cf0?crop=entropy&cs=srgb&fm=jpg&q=85&w=1200"],
       "Phone, laptop, and earbuds — one compact charger does it all.",
       "A GaN fast charger with three ports that's small enough to forget it's in your bag.",
       "One charger for everything you carry. Volt is tiny, fast, and means one less thing to pack.",
       ["65W total across 3 ports", "Charges laptops and phones", "Compact GaN design", "Foldable pins for travel"],
       ["Plug it into any socket", "Connect up to 3 devices", "Fast-charge them all at once"],
       [{"label": "Output", "value": "65W total"}, {"label": "Ports", "value": "2x USB-C, 1x USB-A"}, {"label": "Tech", "value": "GaN"}],
       ["Volt charger"],
       badge="Best Seller", best_seller=True, related=["roll-cable-organizer", "peak-power-bank", "aura-wireless-charger"]),

    _p(11, "halo-motion-light", "Halo Motion Light", "Light that knows when you're there.", "home",
       899, 1299,
       ["https://images.unsplash.com/photo-1552858725-2758b5fb1286?crop=entropy&cs=srgb&fm=jpg&q=85&w=1200"],
       "Warm light that switches on the moment you walk by.",
       "A rechargeable motion-sensor light for hallways, wardrobes, and midnight kitchen runs.",
       "No more fumbling for switches in the dark. Halo lights your way and switches itself off when you leave.",
       ["Turns on with motion", "Soft, warm glow", "Magnetic, stick-anywhere mount", "Rechargeable — no wiring"],
       ["Stick it where you need light", "Walk past it", "It lights up, then turns off on its own"],
       [{"label": "Sensor", "value": "Motion + light"}, {"label": "Battery", "value": "Rechargeable"}, {"label": "Mount", "value": "Magnetic"}],
       ["Halo light", "Magnetic mount", "USB-C cable"],
       badge="New Drop", related=["glow-led-strip", "ease-neck-massager"]),

    _p(12, "peak-power-bank", "Peak Power Bank", "A full day of battery in your pocket.", "everyday-carry",
       1599, 2199,
       ["https://images.unsplash.com/photo-1585995603413-eb35b5f4a50b?crop=entropy&cs=srgb&fm=jpg&q=85&w=1200",
        "https://images.unsplash.com/photo-1557767382-97b28f5488e7?crop=entropy&cs=srgb&fm=jpg&q=85&w=1200"],
       "Fast-charges your phone twice over, anywhere.",
       "A slim 10,000mAh power bank that fast-charges your phone and slips into a pocket.",
       "Low battery anxiety, gone. Peak keeps your phone alive through travel days, long shifts, and nights out.",
       ["10,000mAh — ~2 full phone charges", "Fast USB-C in and out", "Slim, pocketable body", "Charges two devices at once"],
       ["Charge the power bank", "Plug in your phone", "Top up on the move"],
       [{"label": "Capacity", "value": "10,000mAh"}, {"label": "Ports", "value": "USB-C + USB-A"}, {"label": "Output", "value": "20W fast charge"}],
       ["Peak power bank", "USB-C cable", "Pouch"],
       best_seller=True, related=["volt-gan-charger", "roll-cable-organizer", "aura-wireless-charger"]),

    _p(13, "trek-air-pump", "Trek Air Pump", "A pump that fits in your hand.", "travel",
       1999, 2699,
       ["https://images.unsplash.com/photo-1732194392644-d1b9d92f90c8?crop=entropy&cs=srgb&fm=jpg&q=85&w=1200",
        "https://images.unsplash.com/photo-1672149171729-d3fdcc395fcf?crop=entropy&cs=srgb&fm=jpg&q=85&w=1200"],
       "Inflate tyres, balls, and cycles — cordless.",
       "A cordless electric pump that inflates tyres and more, with a preset pressure you can set and forget.",
       "Flat cycle tyre before a ride? Trek handles it in a minute — no petrol pump, no foot pump, no fuss.",
       ["Cordless and rechargeable", "Set-and-stop pressure", "Built-in light for night use", "Fits bikes, balls, cycles and more"],
       ["Pick your target pressure", "Attach the nozzle", "Press start — it stops on its own"],
       [{"label": "Battery", "value": "Rechargeable"}, {"label": "Max pressure", "value": "150 PSI"}, {"label": "Charging", "value": "USB-C"}],
       ["Trek pump", "Nozzle set", "USB-C cable", "Pouch"],
       related=["peak-power-bank", "volt-gan-charger"], available=False),
]
